conf.py
team.html

Redirect https://www.generic-mapping-tools.org/team.html to GMT AUTHORS.md

Add team.html, redirecting to AUTHORS.md

---

projects/index.rst

Link was right but text was wrong in #14

Fix link text for GMTSAR github page

---

workshops/index.rst

Quick ad for the upcoming half-day [PyGMT workshop](https://2019.foss4g-oceania.org/schedule/2019-11-12?sessionId=SPGUQV) I'll be hosting on 12 November 2019 during the [FOSS4G SotM Oceania 2019](https://2019.foss4g-oceania.org/) conference in Wellington, New Zealand. See also https://github.com/GenericMappingTools/pygmt/issues/317.
Don't have a working repository yet but I'll make sure to have that up soon!

Add details for PyGMT Workshop at FOSS4G Oceania 2019

---

download/index.rst

Add links for 4.5.18 and also separate the download page into sections to make it more readable.
screenshot:

Add links for 4.5.18

---

index.rst

I guess we forgot to add it to the front page.

Add FOSS4G PyGMT workshop to front page news

---

_templates/navbar.html
conf.py
index.rst

Include the link with the Discourse icon. Also include links in the
sections of the index page to all other pages, including Github and the
forum.

Add forum link in nav bar an index page

---

conf.py

The logo isn't readily recognizable so some users might have a hard time
finding the link to the forum. Leave it in the "social_icons" section so
that the link is opened in a new tab instead.
As suggested by @KristofKoch [in the forum](https://forum.generic-mapping-tools.org/t/visibility-of-forum-in-site-navigation-posting-rules/266).

Replace Discourse logo with "Forum"

---

index.rst

The front page was mentioning geodesy but the first workshop is on map and movie making.

Synchronize workshops with index

---

.github/workflows/build.yml

It's a security risk for actions that read encrypted secrets (variables):
https://julienrenaux.fr/2019/12/20/github-actions-security-risk/

Don't use tags in GitHub Actions

---

index.rst

We forgot to add GMT 6.1.1 to the "latest releases" section.
I aslo remove the entries for the old GMT 6.0.0 candidates.

Add GMT v6.1.1 to the latest releases

---

conf.py

Sphinx reports following warning:
```
conf.py:99: RemovedInSphinx40Warning: The app.add_stylesheet() is deprecated. Please use app.add_css_file() instead.
app.add_stylesheet("style.css")
```

Fix deprecated sphinx configurations

---

conf.py
download/index.rst
index.rst
mirrors/index.rst

In this PR, I add a separate page/tab to list the mirrors of the GMT FTP site and data server. The "Downloads" page is also updated accordingly.
**Preview:** https://website-git-mirrors.gmt.vercel.app/
Please check the "Downloads" and "Mirrors" pages to see if you agree with these changes.

List GMT mirrors in a separate page

---

about/index.rst

Add in the latest Geoinformatics grant and mention GMT 6 release in 2019.

Update grants and mention GMT 6

---

mirrors/index.rst

Reformat the mirror table using the `list-table` directive. So we can control the widths of each column and don't need to care about the length of `=` signs like the old table.
**New:**
**Old**:

Reformat the mirror table

---

about/index.rst

Add OCE-1558403, OCE-1841660, EAR-1347184.
OCE-1648602 is not added.
Closes https://github.com/GenericMappingTools/pygmt/issues/860

Add more GMT grants

---

conf.py
index.rst

Announce that we have a twitter handle (https://twitter.com/gmt_dev) on the News and add a Twitter icon link on the top-right.
Preview at https://website-git-fork-weiji14-twitter-gmt.vercel.app
Closes #99

Add twitter icon and news announcement

---

mirrors/index.rst

It otherwise fails if not accessed for a few minutes.

Use direct URL in shields check for NOAA

---

index.rst
workshops/index.rst

This PR adds the 2021 UNAVCO workshop to the workshop page and the announcements page.

Add 2021 UNAVCO Workshop

---

documentation/index.rst
download/index.rst
index.rst

Include links to GMT 6.2.0 release candidate 1. Xref https://github.com/GenericMappingTools/gmt/issues/5070

Update release information for 6.2.0rc1

---

index.rst

This PR adds the Ian McHarg Medal Lecture to the news on the main page.

Add Ian McHarg Medal Lecture to news

---

index.rst

This PR adds a sentence about the wrappers in the first summary paragraph on the website landing page. I think this prominence is helpful, since some people may not scroll all the way to the "C, MATLAB, Julia, Python section". Comments are welcome. Here is what the change looks like:
Preview link: https://website-3101vnw0c-gmt.vercel.app/

Highlight wrappers in the summary paragraph

---

index.rst
news/index.rst

This PR migrates some of the older news items from the landing page to the news page, because the list was getting long relative to the releases and workshops lists.
Based on the conversation at https://github.com/GenericMappingTools/website/pull/95, I removed rather than migrated the news about the release of 6.1.0 and postdoc advertisement.

Move older news from front page to news page

---

_static/style.css
index.rst

This PR includes badges that link to the latest releases for GMT, GMT.jl, and PyGMT on the GMT homepage rather than the last several GMT releases, which can still be found by clicking `more >>`.
Current version:
Suggested version:

Include links to latest releases from the wrappers on the homepage

---

index.rst

This PR adds a news item about the remote datasets upgrade and removes the news items about PyGMT and GMT releases, because those can be seen in the latest releases section of the page.
Addresses https://github.com/GenericMappingTools/remote-datasets/issues/18.

Add remote datasets and remove releases from news items

---

index.rst
workshops/index.rst

Include new date/time, GitHub repository and registration link. Also revised duration from 3.5 to 1.5 hours.

Update EGU22 PyGMT short course information

---

mirrors/index.rst

This PR updates the name of the OpenTopography mirror to match the format expected by the GMT_DATA_SERVER setting.

Update name for OpenTopography mirror to match address

---

documentation/index.rst
download/index.rst

Update website following 6.4 release.  Note the checklist says to update the news section but I think we stopped adding those items as we have the auto-generated glyphs showing the latest ?

Move to 6.4

---

index.rst
workshops/index.rst

Mastering Geospatial Visualizations with GMT/PyGMT at AGU Fall Meeting 2024.
See also:
- https://forum.generic-mapping-tools.org/t/agu-2024-pre-conference-workshop/4817
- https://github.com/GenericMappingTools/agu24workshop

Add AGU 2024 pre-conference workshop to upcoming workshops

---

index.rst
workshops/index.rst

This PR moves the AGU24 GMT/PyGMT pre-conference workshop from "upcoming" to "past" workshops (https://www.generic-mapping-tools.org/workshops/).
Just wondering, if we should list the Union Session on GMT also somewhere?
Patches: #155

Move AGU24 preworkshop from upcoming to past workshops

---

cite/index.rst

Add the paper "The Origins of the Generic Mapping Tools: From Table Tennis to Geoscience" to the citation page.

Add the "GMT origin" paper
