GenericMappingTools/website

- about/index.rst
- index.rst
- projects/index.rst
Also removed Louise Kellog from the committee.
> Adding some draft decriptions

- about/index.rst
Embed the video in the About page and also link to the original.
> Add a video of Paul's 20 years of GMT talk

- projects/index.rst
@joa-quim I got some text from the GMT.jl README. Is this OK? Feel free to add anything to this branch if you want.
> Add description for GMT.jl

- download/index.rst
> Add GMT FTP mirrors to the download page

- index.rst
- workshops/index.rst
Now that the link is known we add it to the site.
> Add linke to AGU2019 workshop

- documentation/index.rst
> Update the link to GMT4 docs and add a link to GMT 6.0 docs

- index.rst
> Add the GMT6 paper to news

- documentation/index.rst
- download/index.rst
- index.rst
Announce on first page, update download and documentation links
> Add GMT 6 release

- index.rst
Include it in the news feed with links to SOEST and EGU announcements.
> Add announcement for Paul's 2020 EGU award

- download/index.rst
> Add links to GSHHG and DCW data

- index.rst
- workshops/index.rst
The FOSS4G workshop is over. Move it to past workshops.
> Move FOSS4G workshop to past workshops

- conf.py
> Add the link to GMT YouTube channel

- index.rst
> Make it clear that GMT is free and open source

- index.rst
- workshops/index.rst
> Move AGU2019 workshop to the past

- index.rst
- workshops/index.rst
> Add 2020 GMT workshop

- cite/index.rst
> Add the citation information for GMT/MATLAB

- workshops/index.rst
TBD is still instructors and repo URL.
> Update the known dates for 2020

- about/index.rst
Output format is now flexible.
> Not focus on making PostScript anymore

- download/index.rst
Address https://github.com/GenericMappingTools/gmt/issues/2275
> Update links for GSHHG and DCW data

- workshops/index.rst
One-day user workshop for new users to GMT 6 modern mode.  Held at UH in conjunction with the Goldschmidt conference.  Registration via the conference only [$60] cost.
> Add workshop for Goldschmidt conference in Honolulu

- index.rst
The succession grant is now public so adding it here.
> Add latest grant to the website

- index.rst
Ping https://github.com/GenericMappingTools/pygmt/issues/418
> Add the news for PyGMT v0.1.0

- index.rst
- workshops/index.rst
Not doing that one, but we are doing UNAVCO.
> Cancel the Goldschmidt workshop

- index.rst
Preview:
Is this what you want? Two links. One for the Google docs and one for the application link?
> Add the GMT postdoc add

- index.rst
> Clarify the GMT article is open acces

- index.rst
- workshops/index.rst
Leave cancelled GOldschmidt in the past
> Move to UNAVCO workshop

- index.rst
Moved the news section to the end as discussed in #55 
Also changed the background zebra into the right order
Fixes #55
> Moved the news section to the end

- index.rst
The link goes to the forum announcement.
> Add 6.1 news link

- documentation/index.rst
- download/index.rst
- index.rst
- news/index.rst
- workshops/index.rst
Also update some older news items.
> Update website for 6.1.1 release

- conf.py
> Add "Try Online" in the menu bar

- mirrors/index.rst
Screenshot: 
Closes https://github.com/GenericMappingTools/gmtserver-admin/issues/79.
> Add badges for mirror status

- mirrors/index.rst
This PR adds some instructions to set up a GMT FTP mirror and data server mirror. Feel free to make any changes if the sentences don't read well.
Closes #21.
Closes https://github.com/GenericMappingTools/gmtserver-admin/issues/80.
**Screenshot:**
**Preview**: https://website-git-mirror-instructions.gmt.vercel.app/mirrors/#becomming-a-gmt-mirror
> Add instructions to set up GMT mirrors

- mirrors/index.rst
Typos etc.  However, do we not also need to add some instructions to those who may want to serve up the data? They would need to set up a web server, no?
> Fix some wordings

- mirrors/index.rst
Before we go live with this, we should at least discuss if the USTC mirror should be "asia" or "china".
> Add China and acknowledgements

- mirrors/index.rst
Also extend table with host institution name. Let me know if the formatting of the revised table can be improved. @joa-quim, please help with your host information if it should be more detailed.
> Add South AFrica mirror

- _static/style.css
- mirrors/index.rst
> Highlight the master host

- mirrors/index.rst
> Add Singapore National University

- mirrors/index.rst
Checking status of a domain doesn't gurateen that a mirror is running correctly.
Instead, we can check if the link to the `gmt_data_server.txt` file is
valid and the status is OK, so that we know that the mirror is running
correctly.
> Checking if gmt_data_server.txt exists in the mirrors

- mirrors/index.rst
EarthBYte now offers up both the program mirror and the data mirror
> Add the Australia mirror

- mirrors/index.rst
The last two mirrors for now - still awaiting UNAVCO.
> Add NOAA and Brasil mirrors

- _static/style.css
- mirrors/index.rst
**Changes:**
1. Move the acknowledgment to the top
2. Highlight the master FTP server
3. Change the background color of the master server
**Screenshot:**
> Address more inconsistences in #88

- mirrors/index.rst
> Let users report to us if any mirrors are offline

- documentation/index.rst
- download/index.rst
- index.rst
Affects listing of releases, the documentation, and download pages.
> make updates for 6.2

- index.rst
Add information about release of PyGMT version 0.4.0.
>  Update index.rst to announce release of PyGMT 0.4.0

- download/index.rst
- index.rst
- workshops/index.rst
> Update website information

- download/index.rst
> Update to DCW 2.0.2

- mirrors/index.rst
Doing another push with UNAVCO so wanted to update this first.
> Update size needed for mirrors

- mirrors/index.rst
> Add OpenTopgraphy/SDSC to data mirror list

- download/index.rst
> Update DCW version

- index.rst
We forgot to add the workshop.  This also adds the "major award"
> Add top download and UNAVCO course

- conf.py
- index.rst
- workshops/index.rst
closes https://github.com/GenericMappingTools/website/issues/135
> Add 2022 UNAVCO workshop info

- workshops/index.rst
Routine moving to past section.
> Move UNAVCO to past workshops

- index.rst
> Remove upcoming workshop

- environment.yml
- index.rst
- news/index.rst
@Esteban82 could you please share on Instagram? Here is the twitter post - https://twitter.com/gmt_dev/status/1617342107798077449
> Add YouTube links to Ian McHarg Medal Lecture and Greg Leptoukh Lecture

- index.rst
Just a short entry in the news list.
> Mention the Oslo summit

- workshops/index.rst
We forgot to update this before the workshop; at least this will be a recod of what happened.  Since I did not participate, please update this PR with factulal names and dates!
> Add recently past workshop info

- index.rst
> Remove news about working on GMT 6.5

- about/index.rst
I add Pauls' 2024 paper in the "History" section.
> Update about page. Add Pauls 2024 paper.

- cite/index.rst
Make sure all references are consistently in the AGU style.
> Reformat all reference citations using the AGU style

- cite/index.rst
- news/index.rst
> Add GMT Animation in NEWS and CITE

- workshops/index.rst
Updating AGU24 workshop details based on info at https://agu.confex.com/agu/agu24/meetingapp.cgi/Session/226736
Patches #155
> Add JupyterBook site for AGU24 workshop, update location and session info
